<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * StickerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StickerRepository extends EntityRepository
{
		/****
	returns the number of entity's rows
	@return int
	*/
	public function count() {
		$query = $this->createQueryBuilder('e')
		              ->select('count(e)')
		              ->leftJoin('e.pack', 'p')
		              ->where('p.enabled =  true')
		              ->getQuery();
		return $query->getSingleScalarResult();
	}
}
